# Generated by Django 6.0.2 on 2026-02-04 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('license_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('visited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artwork')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_artworks', to='api.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='artworks',
            field=models.ManyToManyField(related_name='projects', through='api.ProjectArtwork', to='api.artwork'),
        ),
        migrations.AddIndex(
            model_name='projectartwork',
            index=models.Index(fields=['project', 'visited'], name='api_project_project_b8f9b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectartwork',
            unique_together={('project', 'artwork')},
        ),
    ]
