# Generated by Django 6.0.2 on 2026-02-04 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ProjectArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('visited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artwork')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_artworks', to='api.project')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='artworks',
            field=models.ManyToManyField(related_name='projects', through='api.ProjectArtwork', to='api.artwork'),
        ),
        migrations.AddIndex(
            model_name='projectartwork',
            index=models.Index(fields=['project', 'visited'], name='api_project_project_b8f9b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectartwork',
            unique_together={('project', 'artwork')},
        ),
    ]
